#!/usr/bin/env bash
set -e
name="{{#lowerCase}}{{name}}{{/lowerCase}}"
if ! [[ -x "$(command -v realpath)" ]]; then
  if [[ "$OSTYPE" == "darwin"* ]]; then
    brew install coreutils
  fi
fi

SCRIPT_LOCATION=$(realpath "${0%/*}/")

if [ "${SCRIPT_LOCATION}" == "/usr/local/bin" ]; then
  # When called via /usr/local/bin reverse symlink back to the project root
  THIS_SCRIPT=$(realpath "/usr/local/bin/${name}")
  ROOT=$(dirname "${THIS_SCRIPT}")
else
  # Navigate to project root, allows execution from everywhere with correct relative links
  ROOT=$SCRIPT_LOCATION
fi

SIDEKICK_PACKAGE="${ROOT}/packages/${name}_sidekick"
SIDEKICK_COMMITS=$(git -C "$ROOT" rev-list --count HEAD "${SIDEKICK_PACKAGE}" || echo "0")

EXE="${SIDEKICK_PACKAGE}/build/${name}_sidekick-$SIDEKICK_COMMITS.exe"

if [ ! -f "${EXE}" ]; then
  sh "${SIDEKICK_PACKAGE}/tool/install.sh"
fi

"${EXE}" "$@"