include: package:lint/analysis_options_package.yaml

linter:
  rules:
    avoid_print: false
    unawaited_futures: true
    use_late_for_private_fields_and_variables: false
    # public_member_api_docs: true