name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  core_test:
    runs-on: ubuntu-latest

    container:
      image: dart:3.0.0

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies sidekick_core
        run: cd sidekick_core && dart pub get --no-precompile
      - name: Run tests sidekick_core
        run: cd sidekick_core && dart test

  vault_test:
    runs-on: ubuntu-latest

    container:
      image: dart:2.19.0

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies sidekick_vault
        run: cd sidekick_vault && dart pub get --no-precompile
      - name: Install gpg
        run: apt-get update && apt-get install -y gpg
      - name: Run tests sidekick_vault
        run: cd sidekick_vault && dart test

  plugin_installer:
    runs-on: ubuntu-latest

    container:
      image: dart:2.19.0

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies sidekick_plugin_installer
        run: cd sidekick_plugin_installer && dart pub get --no-precompile
      - name: Run tests sidekick_plugin_installer
        run: cd sidekick_plugin_installer && dart test

  sk_sidekick:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies sk_sidekick
        run: ./sk
      - name: Run tests sk_sidekick
        run: cd sk_sidekick && ./build/cache/dart-sdk/bin/dart test
