name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  core_test:
    runs-on: ubuntu-latest

    container:
      image: dart:2.18.6

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies sidekick_core
        run: cd sidekick_core && dart pub get --no-precompile
      - name: Run tests sidekick_core
        run: cd sidekick_core && dart test

  vault_test:
    runs-on: ubuntu-latest

    container:
      image: dart:2.18.6

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies sidekick_vault
        run: cd sidekick_vault && dart pub get --no-precompile
      - name: Install gpg
        run: apt-get update && apt-get install -y gpg
      - name: Run tests sidekick_vault
        run: cd sidekick_vault && dart test

  plugin_installer:
    runs-on: ubuntu-latest

    container:
      image: dart:2.18.6

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies sidekick_plugin_installer
        run: cd sidekick_plugin_installer && dart pub get --no-precompile
      - name: Run tests sidekick_plugin_installer
        run: cd sidekick_plugin_installer && dart test
